repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.17
    hooks:
      - id: ruff
        args: [--fix, --config, packages/python/pyproject.toml]
      - id: ruff-format
        args: [--config, packages/python/pyproject.toml]
